[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "StonedFenicsx"
version = "0.0.0-alpha"
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy==2.2.6",
    "scipy>=1.15",
    "gmsh==4.13.1",
    "pandas==2.3.3",
    "meshio==5.3.5",
    "numba==0.61.2",
    "myst-parser",
    "piccolo_theme",
    "sphinxcontrib-bibtex",
    "pyyaml==6.0.3",
    "h5py==3.12.1",
    "shapely==2.1.2", 
]

[project.urls]
Homepage = "https://github.com/APiccolo89/StonedFenicsx"

# Forgot to say where when I updated the layout of the project, I use this as reminder for eternity
[tool.setuptools.packages.find]
where = ["src"]
include = ["stonedfenicsx*"]

[tool.pytest.ini_options]
testpaths = ["tests"]












# For cluster user in case that Conda is not set up for parallel
#[tool.spack]
#python = "3.11"
#mpi = true
#petsc = true
#dolfinx = true
#h5py = true

# FOR HPC user
# -> Install the software, then load spack 
#spack load py-fenics-dolfinx
#python -m venv stoned_fenicsx
#source stoned_fenicsx/bin/activate
#pip install --no-deps -e .
