#The rheology works using the following formulation:
#\eta = 0.5 * b^-1/n * \dot{\epsilon}^{(1-n)/n} * exp(-(E + PV)/nRT) * COH^-r/n/f_H20^r
#
#Where:
#- \eta is the viscosity
#- b is the pre-exponential factor
#- n is the stress exponent
#- E is the activation energy
#- P is the pressure
#- V is the activation volume
#- r is the water content exponent
#- COH is the water contentß
#- R is the gas constant
#- T is the temperature
#The data most of the time have different rheological apparatus, are listed with weird unit of measure
#the data base is conceived to put the relevant information to convert the pre-exponential factor into Pa^-n s^-1.
Common: 
  n: 1.0
  m : 0.0
  d : 1.0
  ah2o: 1.0
  bh2o: 5521e6 
  eh2o: 31.28e3 
  vh2o: -2.009e-5 


Diffusion_creep: 
  Diffusion_DryOlivine: 
    b: 1.5e9
    e: 375.0e3
    v: 5e-6
    f: 'Simpleshear'
    d: 10e3
    mpa: 1
    r: 0
    m: 3.0
    b_si: 'MPa^-1s^-1'
    water_correction: 'None'
    ref: 'Hirth, Greg, and David Kohlstedt. "Rheology of the upper mantle and the mantle wedge: A view from the experimentalists." Geophysical monograph series 138 (2003): 83-105.'
  Diffusion_WetOlivine: 
    b: 2.7e7
    e: 375.0e3
    v: 10e-6
    f: 'Simpleshear'
    d: 10e3
    mpa: 1
    r: 0.8
    m: 3.0
    b_si: 'MPa^-1 s^-1 COH^-r'
    water_correction: 'COH'
    ref: 'Hirth, Greg, and David Kohlstedt. "Rheology of the upper mantle and the mantle wedge: A view from the experimentalists." Geophysical monograph series 138 (2003): 83-105.'
  Diffusion_vanKeken: 
    b: 3.7866452594987994e-10
    e: 335.0e3
    v: 0e-6
    f: 'None'
    d: 1.0
    mpa: 0
    r: 0.8
    m: 1.0
    b_si: 'Pa^-1 s^-1'
    water_correction: 'None'
    ref: 'van Keken, Peter E., et al. "A community benchmark for subduction zone modeling." Physics of the Earth and Planetary Interiors 171.1-4 (2008): 187-197.'
    note: 'I did not find the original data for this flow law. I converted the value to be consistent with the formulation of the '


Dislocation_creep:
  Dislocation_DryOlivine: 
    b: 1.1e5
    e: 345.0e3
    v: 15e-6
    f: 'Simpleshear'
    mpa: 1
    r: 0.0
    n: 3.5
    b_si: 'MPa^-n s^-1'
    water_correction: 'None'
    ref: 'Hirth, Greg, and David Kohlstedt. "Rheology of the upper mantle and the mantle wedge: A view from the experimentalists." Geophysical monograph series 138 (2003): 83-105.'

  Dislocation_WetOlivine: 
    b: 1600
    e: 520.0e3
    v: 22e-6
    f: 'Simpleshear'
    mpa: 1
    r: 1.2
    n: 3.5
    b_si: 'MPa^-ν s^-1 COH^-r'
    water_correction: 'COH'
    ref: 'Hirth, Greg, and David Kohlstedt. "Rheology of the upper mantle and the mantle wedge: A view from the experimentalists." Geophysical monograph series 138 (2003): 83-105.'

  Dislocation_WetPlagio: 
    b: 2.7e7
    e: 345.0e3
    v: 38e-6
    f: 'Uniaxial'
    d: 10e3
    mpa: 1
    r: 0.0
    n: 3.0
    b_si: 'MPa^-n s^-1'
    water_correction: 'None'
    ref: 'later'
    note: 'Data have been pre-processed in the original source. Water is not explicitly listed'
  
  Dislocation_serpentinite:
    b: 2.82e-15
    e: 8900 
    v: 3.2e-6
    f: 'Uniaxial'
    n: 3.8
    mpa: 1 
    water_correction: 'None'
    r: 0.0
    b_si: 'MPa^-n s^-1'
    ref: 'Hilairet, N., et al. High-pressure creep of serpentine, interseismic deformation, and initiation of subduction. (2007)'
  
  Dislocation_wetquartzite: 
    b: 6.309573444801943e-12
    e: 135.0e3
    v: 0e6
    f: 'Uniaxial'
    n: 4.0
    mpa: 1
    water_correction: 'Fugacity'
    r: 1.0 
    b_si: 'MPa^-(n+r) s^-1'
    ref: 'Hirth, G., Teyssier, C. & Dunlap, James W., An evaluation of quartzite flow laws based on comparisons between experimentally and naturally deformed rocks, 2001'

  Dislocation_glaucophane: 
    b: 2.32e10 
    e: 450.0e3 
    v: 0e-6
    n: 3.0 
    r: 0.0
    f: 'Uniaxial'
    mpa: 1
    water_correction: 'None'
    b_si: 'MPa^-n s^-1'
    ref: 'blueschist dislocation creep and glide in subduction systems: Constraints from glaucophane experiments'
