name: test_git_action

on: # Tell to do these checks only during pull request to main
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-linux: 
    name: test_git_action
    runs-on: ubuntu-latest

    permissions: # Tell that it can write
      contents: write

    steps:
      - uses: actions/checkout@v4 # use the action

      - name: Set up Python 3.13
        uses: actions/setup-python@v3 # setup pythonv3
        with:
          python-version: '3.13' # Use this version of python
 
      - name: Add conda to system path # Add conda to path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies # Install dependency
        run: |
          conda env update --file stonedenvironment.yml --name base

      - name: Test with pytest and coverage # run all the tests
        run: |
          pytest --cov=stonedfenicsx --cov-report=xml

  post-test: # Deployment enviroment => This must succed to be able to push to master
    needs: build-linux
    runs-on: ubuntu-latest

    environment:
      name: post-test

    steps:
      - name: Post-test successful
        run: echo "Tests passed successfully."


# git actions => do the test job => status check => rule set => yes/no merging 